theme: jekyll-theme-minimal
title: Yu Mo
description: Research Fellow at the University of Oxford
logo: https://www.oxfordsparks.ox.ac.uk/wp-content/uploads/2022/06/Yu-Mo.jpg
show_downloads: false
markdown: GFM

